# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('BookNo', models.CharField(max_length=11, unique=True)),
                ('BookName', models.CharField(max_length=30)),
                ('BookWriter', models.CharField(max_length=30)),
                ('BookPublish', models.CharField(max_length=30)),
                ('BookPrice', models.IntegerField()),
                ('BookDate', models.DateField(blank=True, null=True)),
                ('BookClass', models.CharField(blank=True, max_length=30, null=True)),
                ('BookMain', models.TextField(blank=True, null=True)),
                ('BookPrim', models.CharField(blank=True, max_length=255, null=True)),
                ('BookState', models.BooleanField(default=True)),
                ('BookRNo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=30, unique=True)),
                ('default', models.BooleanField(db_index=True, default=False)),
                ('permissions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='token')),
                ('LastTime', models.DateTimeField(auto_now=True)),
                ('expire', models.BigIntegerField(verbose_name='expire')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('UserName', models.CharField(blank=True, max_length=30, null=True)),
                ('MaxBorrowNumber', models.IntegerField(default=15)),
                ('BorrowNumber', models.IntegerField(default=0)),
                ('UserSex', models.CharField(blank=True, max_length=1, null=True)),
                ('UserPhone', models.CharField(blank=True, max_length=11, null=True)),
                ('UserAddr', models.CharField(blank=True, max_length=255, null=True)),
                ('RegisterDate', models.DateTimeField(auto_now_add=True)),
                ('Fine', models.IntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('RoleName', models.ForeignKey(default='\u8bfb\u8005', on_delete=django.db.models.deletion.CASCADE, to='myapp.Role', to_field='RoleName')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowInfo',
            fields=[
                ('BookID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Book')),
                ('BorrowTime', models.DateTimeField(auto_now_add=True)),
                ('BackTime', models.DateTimeField()),
                ('ReaderID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='FineInfo',
            fields=[
                ('BookID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Book')),
                ('Fine', models.IntegerField()),
                ('ReaderID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
