# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=30, unique=True)),
                ('default', models.BooleanField(db_index=True, default=False)),
                ('permissions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='token')),
                ('LastTime', models.DateTimeField(auto_now=True)),
                ('expire', models.BigIntegerField(verbose_name='expire')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('UserName', models.CharField(max_length=30, null=True)),
                ('UserSex', models.CharField(max_length=1, null=True)),
                ('UserPhone', models.CharField(max_length=11, null=True)),
                ('UserAddr', models.CharField(max_length=255, null=True)),
                ('RegisterDate', models.DateTimeField(auto_now_add=True)),
                ('Fine', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
