# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LostBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayMoney', models.IntegerField()),
                ('OperateDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='borrowinfo',
            name='RenewState',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fineinfo',
            name='OperateID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fine_admin', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='fineinfo',
            name='PayDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fineinfo',
            name='PayState',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='TotalBorrow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookClass',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.BookClasses'),
        ),
        migrations.AlterField(
            model_name='borrowinfo',
            name='BackTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrowinfo',
            name='BorrowTime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fineinfo',
            name='ReaderID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine_reader', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='lostbook',
            name='BookID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Book'),
        ),
        migrations.AddField(
            model_name='lostbook',
            name='OperateID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lost_admin', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='lostbook',
            name='ReaderID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lost_reader', to='myapp.User'),
        ),
    ]
