# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_rolename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='RoleName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Role', to_field='RoleName'),
        ),
    ]
