# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='RoleId',
            new_name='id',
        ),
    ]
