# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160622_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='RoleName',
            field=models.ForeignKey(default='\u8bfb\u8005', on_delete=django.db.models.deletion.CASCADE, to='myapp.Role', to_field='RoleName'),
        ),
    ]
