# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160622_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='CodeTime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='VerificationCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='MaxBorrow',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
