# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160622_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='VerificationCode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
