# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160620_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='RoleID',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserAddr',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserPhone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserSex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
